language: node_js
node_js:
- node
cache: npm
script:
- npm run coverall
- npm run build
branches:
  only:
  - master
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: M7K4tYNyudszL0gzZENT3szKnL4IJqfKTJQ51U9YHu35JmWYyyM7XErIVy1XqRz7xnCbjc3gcIkrdTzq9BxzmYxFLGLgwJmktwPwHprwilEyiyXrPrvKrpju5jrdLipm0ih+UcmWLjt/0zJ/kdwCfGX5KoT7hkCE28gFx/PknOm1wZvXUSfsXAgZ96N1vgUKvfJjGy+mPQgTfh0zQOh3XZJrmkkkKT0s2uQNxYdPiO4nvxoFEpoLYjQ/XrnKWl/WrJTCnf6l0GQcj5QkHrrT4fnncgj7Zcf1m5lUquq7y3t8Bkmd7MEhl+TrM+97WuSEBczp8loLvpkLz/XX/8p2M8cdyLX8mIe9jYhuFzWc6Rh11N0X19FRps5fTgYgDXJODCOkg+yntp3384FnSvPvlTlzdwsWdpkR5Fje7UPWgLKf5/L6FFIynD3oIJRD7UUAzkGxuAJ61cmS+PCzeweSlwusAkO8el8sIERCtv9olUsywasulyr9msuG/4RaAFjA9g0iVHAL3E4cygBLIAvtoDI7ZaMIu/1B77Q8QmjBU7LXQl6tWGFvac1+pmj69dh2BngpzmuBhoe3hm43yGbgAPMp9u03TyJ7j1Q67b4YQo82nD4Bp3Xib7tS0lY0dVtJV/wm6+DYoS6oEIGPhUp1cmSWFOnrfWOHJ5kXMZ1cyfE=
  app:
    master: bongo-faces-staging
    production: bongo-faces-production
notifications:
  slack:
    secure: Q7T0ZI6wUCQoySggyqhtLybxqRbfqLGvSZELUPCHjRwF42Ju4aOF0RvAv12ATYM62Mf40hEF9kg+UfOjMKEpG19oOPyFs+b1+AjME0CI5qxb5VuVdUqvSCJ1DLfQt0LwI+vxRCK3mow+n57bMh6v0nTjVC9V4Mhm2sikT+T6xjLd95NDnbmjDILO4j78F6eSVa7MiPZ9Nlsa9n8AAVyHCvxBKdFDXEsKcZeMHLob7VCNiXH6MGsFMtVC7ayEtDtiAhZ6qvLsyF+ZdKsT1nxa5cxlZscXTHEMbS5X/mvdjTfOw3qyK2xY361RphRCfLoWx5xVoKajxnxl6U9IoT/7i+LYXkHAu4P8vhKhdQa9fAEYbLX6f3efFbTY2emFD8UTSVdiqo55CvGKQ3V5I/KXw9iZzebrvSWTgCv8Wj92NdVHaTU8Bq3PgNJBj9cloYGGiLEK3thfQLCPLDQHEIlNQze4mipXvR0iIFDoEozf3KPUmlhaIA2VDt5tK91byuqgHWPaVxPTCbw+DbNev05wkm8W6P7/csfl8Tqz+D61O9R/Smi/bnHopPsS2715lY6JmM6a9C7595McJgK3CMCBNV6cVrlPoeNcIIh9+Xh4u9K6Xc0yAPr2vOihxlVwdmEHILiZIKjbXpiFzEx1PmcsRvv4+uLJWregMj0iTXrkv+A=
